### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by quatquatt** [audaki/minecraft-cart-engine#12]
Plans to update to 1.19?

**Comment by M-Ryba** [comment]
Would also love to see it updated (thank you for this awesome mod btw)

**Comment by Cm4nXD** [comment]
+1 for 1.19 update

**Comment by audaki** [comment]
I'm publishing an update now. I've changed the version to be >=1.19 since Mojang doesn't seem to change the relevant code very often so usually it works for future minecraft versions as well.

**Comment by audaki** [comment]
@Cm4nXD @M-Ryba @quatquatt @raspopov @subatomic-olive

Update is available here now: https://www.curseforge.com/minecraft/mc-mods/audaki-cart-engine/files
