### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [audaki/minecraft-cart-engine#14]

**Comment by audaki** [comment]
@sternschnaube Thanks for the issue. I did not know that I need to mark sub versions like 1.19.3 as compatible

Do you know if there is a service where you can get notifications for new minecraft versions?

**Comment by sternschnaube** [comment]
Hello ☺️

The Devs was saying, we get more often minor versions - but with more or less bigger changes. The switch from 1.19.2 to 1.19.3 was breaking already a lot of mods... I see the struggle in the future already 😫

I use Twitter or "minecraft.net" for this case. But I'm right now not aware of a service specifically for this case. Sorry.

You could activate the notification from one or more Dev / Other related accounts on Twitter 🙌🏿

**Comment by audaki** [comment]
Thanks for the info!

About the issue: I've tested explicitly with 1.19.3 and released a new version here and on CurseForge. It was compatible but I still released an explicitly tested version.

**Comment by sternschnaube** [comment]
Thanks, directly updated.

A bit else... I was asking Patbox recently, if he is willing to update his Mod: https://modrinth.com/mod/tatercart
He told me, that this mod is a big mess (😆😆) but maybe in the future, as a rewrite.

I was telling him, that it would be nicee, if he could **connect** it then with Audakis Cart optimizations.
This would really lead to some perfect Cart optimizations, with pure server-side functionality 🥰

Loving the Minecarts / Railsystem, but Mojang isn't giving it a lot of love in the last years.
Endless potential.

**Comment by audaki** [comment]
@sternschnaube It seems like he solved going fast into ascensions/descensions, but only sometimes (for example it breaks when  Lithium is installed). It's an interesting mod for sure!
