### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by vico93** [audaki/minecraft-cart-engine#16]
Hello! Just found this mod on Modrinth while searching about mods than change minecarts.

I just want to know if it allows something like [TrainCarts](https://wiki.traincarts.net/index.php/TrainCarts)-like minecraft linking (forming trains) and [fully automation of stations](https://wiki.traincarts.net/p/TrainCarts/Signs) and such.

Currently i'm using the plugin mentioned above, but its for Spigot-only, and i'm looking for a replacement native to Fabric.

**Comment by audaki** [comment]
@vico93 Thanks for the interest but these features are out of the scope of this mod. This mod is as vanilla as possible, merely fixing the slow speed of minecarts (while keeping compatibility to all rail layouts and redstone builds).
