### ISSUE TITLE
Not compatible with Create minecart contraptions

### ISSUE THREAD

**Issue by Hypermoron** [audaki/minecraft-cart-engine#18]
- MC version: Fabric 1.19.2, version 0.14.17
- Mod versions: Audaki Cart Engine v2.0.2, Create 1.19.2 v0.5.0.i Patch 3

Audaki Cart Engine prevents the creation of Minecart Contraptions from Create Fabric. Connected blocks above powered Cart Assemblers are supposed to become part of a Minecart Contraption when a minecart goes under the Cart Assembler. Instead, the minecart passes under the Cart Assembler with no effect.

This appears to happen regardless of the velocity of the minecart and the type of rail placed under the Cart Assembler.

**Comment by audaki** [comment]
Heya @Hypermoron
thanks for the issue!

The Create Fabric mod is very complex, but I checked its source code and I wasn't able to find a code or overwrite conflict.

So my first assumption was speed, but you said the issue persists no matter the speed.

I've done some changes that could be able to fix it (I moved the mixin back to the AbstractCartEntity and I only inject into the method now when there is actually a LivingEntity inside of the cart).

Additionally the cart now slows down to vanilla 8m/s on and directly before Detector and Activator Rails (this might also help if you use these to slow down the cart for the Cart Assembler).


Please try this release: https://github.com/audaki/minecraft-cart-engine/releases/tag/v2.0.3

And please report back 😸

**Comment by Hypermoron** [comment]
The minecart contraptions work now, no detector or activator rails needed. Thanks for the quick fix!
