### ISSUE TITLE
Allow compatibility with melontini's "Linkart" mod

### ISSUE THREAD

**Issue by OnehandguyTrue** [audaki/minecraft-cart-engine#19]
The cart engine doesn't apply to linked carts except for carts with an entity riding in them.
[
Example Video](https://www.youtube.com/watch?v=47PwePdytSI)
[Mod Link](https://modrinth.com/mod/linkart)

**Comment by audaki** [comment]
@OnehandguyTrue Do you know how computationally expensive it is to read nbt every single tick for every single minecart? I'm not sure how else I could create cross mod compatibility here.

**Comment by audaki** [comment]
Mods won't be compatible with each other, sorry!
