### ISSUE TITLE
Crash on 1.20

### ISSUE THREAD

**Issue by robynetzan** [audaki/minecraft-cart-engine#20]
What I did:

Got into a minecart and pressed w to move forward

What I expected to happen:

The minecart would move

What happened: The game instantly crashed

Crash log:
[crash-2023-06-07_21.40.14-server.txt](https://github.com/audaki/minecraft-cart-engine/files/11681788/crash-2023-06-07_21.40.14-server.txt)

**Comment by audaki** [comment]
@robynetzan Thanks for the report!

There was a change in the yarn mappings which I didn't update on dev.

Updated the mappings now and released a new version 2.0.4 which should fix this issue.

If it still crashes with the newly released version please reopen this issue 😊 

rgds, Kira
