### ISSUE TITLE
compatibility with VSAS (Variant Sticks & Stuff)

### ISSUE THREAD

**Issue by dadoirie** [audaki/minecraft-cart-engine#21]
I really do like those minecart tweaks and would like to ask if it were possible adding compatibility to [Variant Sticks & Stuff](https://modrinth.com/mod/variant-sticks-and-stuff) as they add some nice variants of the rails?
I tried adding them the #minecraft:rails tag, but this didn't do much :D

**Comment by audaki** [comment]
@dadoirie tbh I don't know how to make it compatible and I'm on vacation now 🥳 

If you or anyone else wants to create a pull request I'd learn via the code and merge it and maintain it.
