### ISSUE TITLE
Multiloader implementation?

### ISSUE THREAD

**Issue by PlayfulPiano** [audaki/minecraft-cart-engine#24]
Considering how the implementation for this mod is fairly vanilla, I was wondering if you could consider making it multiloader compatible (i.e. able to run in forge, neoforge, fabric, quilt with just one jar file). I know there are implementations of this for other mods (Serilum series of mods has this).

**Comment by audaki** [comment]
Thank you for your issue, sadly I have to inform you that I’m no longer interested in making this work on other loaders.
