### ISSUE TITLE
incompatibility with Copper Rail 

### ISSUE THREAD

**Issue by peow** [audaki/minecraft-cart-engine#26]
The Copper Rail (https://modrinth.com/mod/thecopperrail) adds a rail that always directs the cart in a specific direction

![9be951abf3acccdffe829f1767f755a1b89388ae](https://github.com/audaki/minecraft-cart-engine/assets/105888751/d1e41f82-8a7d-43cb-817b-0f9ab8ab7308)

however when using it together with the Audaki Cart Engine mod, the copper rail loses its function, being considered a normal rail

this only happens when the player is driving the cart, when the cart is empty the Copper Rail still works

----------

If it is possible to fix this, I ask you to update to **fabric 1.20.1**

**Comment by audaki** [comment]
Heya, I just checked it and the mod in question is also overriding the function moveOnRail: https://github.com/iluha168/MCTheCopperRail/blob/main/src/main/java/com/thecopperrail/mixin/AbstractMinecartMixin.java#L23C20-L23C30

I don’t know how to properly fix this, but I will accept pull requests as long as they don’t negatively impact performance for people who don’t use this mod.

**Comment by audaki** [comment]
@peow Thank you for the reporting, but it seems like the mods will never be compatible, sorry!

**Comment by Blockmeska** [comment]
@audaki This is fixable, but it's not going to be an easy fix.

Since you're cancelling the entire moveOnRail method if certain conditions are met, any other mods that try to inject into this method are just met with a no longer existing method.

To fix this, you would need to inject code using mixin only into the necessary parts, without removing the original moveOnRail method.

**Comment by audaki** [comment]
@Blockmeska I’d love to see the pull-request for this :innocent:

**Comment by audaki** [comment]
@peow In case you are using minecraft 1.21.3+, you can now use ACE 4.0 which should be compatible with the copper rail
