### ISSUE TITLE
Query about the use of this mod elsewhere.

### ISSUE THREAD

**Issue by ErakAcheron** [audaki/minecraft-cart-engine#32]
Recently a youtuber named Jetstarfish made a video criticizing Minecraft's exploration (in my view, extremely poorly). 

He commissioned a mod to be made based of the ideas the video presented, and made it available for download as a patreon reward. There was general pushback against this distribution method due to it violating Minecrafts EULA by paywalling a mod, and after some deflection that the mod had cost "hundreds of dollars" (comment is now deleted) and thus justified pay-walling it, the mod was made freely available on modrinth and it was stated it would switch to an "early access" patreon system.

Jet offered patreon refunds through DMs due to the thing they paid for being made free (even though refunding everyone who signed up in that time period would be significantly better). 

Now, the mod version listed on modrinth (https://modrinth.com/mod/jbe) states that:
_"Minecart logic adapted from Audaki's Cart Engine. Please check out their work as well!"_
*it links to this github, not the your modrinth page for some reason

**My actual question after all this is**, did the developer(s?) of the mod contact you in any way regarding the use of your work in a manner significant enough to warrant crediting? and if so, were you aware the mod was again developed with the intention of being fully pay-walled?

Apologies if you've already been asked about this, or if you consider this an improper use of the mods github issues lol.

**Comment by audaki** [comment]
@ErakAcheron

omg! This is the first time I hear about this. Before you told me I knew nothing. And I am easy to contact, like you just contacted me.

Jetstarfish never contacted me.

I was never asked for my permission to use my code. And especially not for such a commercialization.

**Comment by ErakAcheron** [comment]
Well, that's not good. I was skeptical when they credited you without mentioning if you'd actually been contacted during development, seems that might've been well-founded.  

You may have gathered I wasn't the biggest fan of Jets video or the mod, so you might want to watch it yourself instead of relying on my admittedly pre-opinionated view: https://www.youtube.com/watch?v=d4tr_hhNZ2s&t=705s
One thing you won't find there is the original pinned comment under Jets video, he's unpinned it to instead link to the modrinth page (or deleted it, it's effectively gone either way):
![image](https://github.com/user-attachments/assets/c579e32d-5361-4e51-966d-b98e295efd03)

I also don't know how much of your code has been used, only that it was apparently enough to warrant crediting you. The mod does appear to be open source though, so I'd assume it's possible to identify what / how much was used (though I don't know enough to look myself lol). Given it isn't just used as a separate library mod they might have changed a bit. 

The generous assumption of this I can see is that your code was factored in _after_ the distribution model changed, but you'd have to reach out to developer (or I guess, someone who had access to the patreon release before it was made public) to actually check that. It's also _possible_ that they mistook your mod as a library mod of sorts because of the term engine in the name? Doesn't in any way justify it's use in a pay-walled mod but might explain why they didn't reach out if it was incorporated later. _**That last bit is very much me being a devil's advocate though.**_

Jet has a discord server and both he and the mod developer have twitter accounts (all linked in the video description), so if you want to contact them those are probably the way to go.

**Comment by audaki** [comment]
@ErakAcheron Hey, nope, they already used my code 7 months ago, and it is very custom and easy to see, that the whole function was copied 1:1 (it is also very different to the code in minecraft vanilla).

And only a week ago they added a credit into the mod (you can see all of this with the public git history).

But I don’t want to waste time messaging them, it will not give any good results. I will leave this issue open though, in case anyone wants to make a video about it idk

**Comment by ErakAcheron** [comment]
@audaki Well then I'm sorry this happened, it's a particularly scummy thing to do. 

Fair enough on not wanting to continue this further with them, I understand not wanting to make a drama out of it and I share your view that it has a low chance of producing any good. 

Sorry for bringing this to your attention, though I am glad you're aware of it now.
