### ISSUE TITLE
Choose top speed

### ISSUE THREAD

**Issue by nmackowiakk** [audaki/minecraft-cart-engine#33]
Hi!
Will there ever be an option to somehow choose the top speed of a minecart line? I have some slow-speed lines and don't want to make them 34 blocks/s. Great mod btw!

**Comment by audaki** [comment]
@nmackowiakk I was thinking about adding a gamerule to set the max speed for all ridden minecarts. but that yet again would not help your case. on the other hand I really don’t want to add custom blocks which would destroy vanilla compatibility. One option would always be the "debug stick" way, where you can just take a vanilla item like a stick and right click a cart to set a speed for example. But that would be only for 1 minecart, and wouldn’t affect other minecarts on the same line.

**Comment by nmackowiakk** [comment]
Idk if this would be possible, but what about clicking the rails of minecart's departure that set the current speed limit?

**Comment by mrburger** [comment]
This may be a suggestion in poor taste, but could there be a config / gamerule to set the default top speed and then also an option to enable "railbeds" in a configurable manner? Gravel Carts did this, but it doesn't have configuration for setting types and the speed factor increase. Could also clamp the top speed to avoid engine problems, so if I type a x10000 speed increase it wont try to do that.

Of course, doing so would require a config library and a way to detect the block under the rail without presenting a boatload of tick lag, while maintaining Vanilla / server-side only compatibility.

**Comment by TheRonGDD** [comment]
There was a plugin that would do incremental speed increase with Redstone blocks under powered rails. The more powered rails in a row with a block the faster you went. Conversely powering a rail any other way reduced speed to normal.

It was required to slow the cart before turns if you had it going too fast.

**Comment by audaki** [comment]
Starting with v4.0.0 you can now use the top speed by using:

/gamerule aceCartSpeed 20

Of course instead of 20 you can use any integer number you want
