### ISSUE TITLE
Permission to use this mod as a base

### ISSUE THREAD

**Issue by AshyBoxy** [audaki/minecraft-cart-engine#35]
I'm not sure where else to contact you about this, but I feel it's important to, especially with the Jetstarfish situation.

I've started working on a mod which is entirely based on the code of this, just with the express purpose of being more compatible with other mods. With how it's a way more complicated implementation than this (in terms of code layout and whatnot I guess). And, with how you've stated that you're not comfortable maintaining something much more complicated than your current implementation, I figured it'd be best to just start it off as a whole new project. Plus I wanted to make it have an api and config and such eventually.

I actually started making it specifically because I started work on a 1.21 port of Jetstarfish's better exploration and I wanted to make sure it was compatible with other minecart mechanic changing mods. With how I have it implemented right now, it already works fine with the copper rail, for example. I'm working on linkart support specifically too.

You can find the WIP repo [over here](https://github.com/AshyBoxy/cart_engine) if you wanna have a look, but it's in a bit of a state as of writing because apparently I managed to stumble across a bug in mixin itself.

If you are okay with this, then it'd be a great help too if you could give the reasoning for some of the constant values used (like `railStopperAcceleration` being specifically `basisAccelerationPerTick * 16`). I know the values work as they are, but knowing why they are what they are would help immensely to adapting it to work better with other mods.

**Comment by audaki** [comment]
Hey, first of all: don’t compare yourself to that person. In that mod the code was copied without any attribution to me for the first months, and no permission was asked, and I wasn’t even informed and my code was used commercially.

You on the other hand are doing everything perfectly.

Thank you for asking!

Feel free to use my code as long as you give some attribution somewhere and provide the mod for free (i.e. you don’t sell the mod).
