### ISSUE TITLE
Minecart not visually moving 4.0.0 - 4.1.0

### ISSUE THREAD

**Issue by Jeefongithub** [audaki/minecraft-cart-engine#41]
I'm noticing a behavior where the minecraft is not visually moving. If the minecart is pushed or if a player gets in and tries to move it the cart remains still visually however the cart is moving and is not represented till a refresh or disconnect reconnect

attaching a zip file containing a video of what I'm seeing

Server info
Debian 12
Java 21.0.3
Fabric 1.21.3
Mods:
ACE 4.0.0
Armor Poser 7.0.0
Cloth Config 16.0.141
Fabric API 0.107.0
Sodium 0.6.0-beta.4
Squaremap 1.3.3
YetAnotherConfigLib 3.6.1

[2024-12-17 21-44-17.zip](https://github.com/user-attachments/files/18174035/2024-12-17.21-44-17.zip)

**Comment by audaki** [comment]
@Jeefongithub thanks for this issue!

Can you (or the player) try installing the mod locally as well, i.e. client-sided, to see if that fixes the issue?

It might very well be that the clients also need to install the mod now.

**Comment by Jeefongithub** [comment]
Installed 4.1.0 on server side and client side and can confirm working now as expected

**Comment by audaki** [comment]
Thanks, I will mark it in the documentation!
