### ISSUE TITLE
[Feature] Make ACE server-side again

### ISSUE THREAD

**Issue by globalista-dev** [audaki/minecraft-cart-engine#42]
Related to #41.

While I assume it's not explicitly planned, I at least have been using ACE for ages as a server-side only mod to enhance the lackluster vanilla minecart features.

I honestly have not looked into your code to see if I could come up with a solution to restore the server-side functionalities, so I don't know if it's even possible. Maybe [Polymer](polymer.pb4.eu) could be used.

Either way, I'll leave this here as a suggestion, because this mod is usually recommended by many as a server-side enhancement mod for SMPs.

**Comment by audaki** [comment]
Sorry, won’t happen.

But, other mod makers can feel free to take up the torch and make a purely server-sided mod again :blush:

**Comment by audaki** [comment]
@globalista-dev it is your lucky day, @AshyBoxy found a good solution to make the mod server-sided again. Will be released soon as 4.2

**Comment by audaki** [comment]
Released
